package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/fernandobandeira/djinn/backend/internal/database/db"
	"github.com/fernandobandeira/djinn/backend/internal/graph/generated"
	"github.com/fernandobandeira/djinn/backend/internal/graph/model"
	"github.com/fernandobandeira/djinn/backend/internal/middleware"
	"github.com/fernandobandeira/djinn/backend/internal/validation"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*db.User, error) {
	requestID := middleware.GetRequestID(ctx)
	r.Logger.Info("Creating new user",
		"firebase_uid", input.FirebaseUID,
		"email", input.Email,
		"request_id", requestID,
	)
	
	// Validate input
	if err := validation.ValidateCreateUserInput(input); err != nil {
		r.Logger.Warn("Invalid user input",
			"error", err,
			"request_id", requestID,
		)
		return nil, err
	}
	
	// Create user in database using sqlc generated code
	params := db.CreateUserParams{
		FirebaseUid: input.FirebaseUID,
		Email:       input.Email,
		Name:        input.Name,
	}
	
	// Handle optional profile image URL
	if input.ProfileImageURL != nil {
		params.ProfileImageUrl = pgtype.Text{
			String: *input.ProfileImageURL,
			Valid:  true,
		}
	}

	user, err := r.Queries.CreateUser(ctx, params)
	if err != nil {
		r.Logger.Error("Failed to create user",
			"error", err,
			"request_id", requestID,
		)
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	r.Logger.Info("User created successfully",
		"user_id", user.ID,
		"request_id", requestID,
	)

	return &user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*db.User, error) {
	requestID := middleware.GetRequestID(ctx)
	r.Logger.Info("Updating user",
		"user_id", id,
		"request_id", requestID,
	)
	
	// Validate input
	if err := validation.ValidateUpdateUserInput(input); err != nil {
		r.Logger.Warn("Invalid update input",
			"error", err,
			"request_id", requestID,
		)
		return nil, err
	}

	// Parse UUID
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Convert UUID to pgtype.UUID
	pgUserID := pgtype.UUID{
		Bytes: userID,
		Valid: true,
	}

	// Get existing user first
	existingUser, err := r.Queries.GetUser(ctx, pgUserID)
	if err != nil {
		r.Logger.Error("Failed to find user",
			"user_id", id,
			"error", err,
			"request_id", requestID,
		)
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// Prepare update params with existing values as defaults
	params := db.UpdateUserParams{
		ID:    pgUserID,
		Email: existingUser.Email,
		Name:  existingUser.Name,
		ProfileImageUrl: existingUser.ProfileImageUrl,
	}

	// Apply updates
	if input.Email != nil {
		params.Email = *input.Email
	}
	if input.Name != nil {
		params.Name = *input.Name
	}
	if input.ProfileImageURL != nil {
		params.ProfileImageUrl = pgtype.Text{
			String: *input.ProfileImageURL,
			Valid:  true,
		}
	}

	user, err := r.Queries.UpdateUser(ctx, params)
	if err != nil {
		r.Logger.Error("Failed to update user",
			"user_id", id,
			"error", err,
			"request_id", requestID,
		)
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	r.Logger.Info("User updated successfully",
		"user_id", user.ID,
		"request_id", requestID,
	)

	return &user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	requestID := middleware.GetRequestID(ctx)
	r.Logger.Info("Deleting user",
		"user_id", id,
		"request_id", requestID,
	)

	// Parse UUID
	userID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	// Convert UUID to pgtype.UUID
	pgUserID := pgtype.UUID{
		Bytes: userID,
		Valid: true,
	}

	// Delete user
	err = r.Queries.DeleteUser(ctx, pgUserID)
	if err != nil {
		r.Logger.Error("Failed to delete user",
			"user_id", id,
			"error", err,
			"request_id", requestID,
		)
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	r.Logger.Info("User deleted successfully",
		"user_id", id,
		"request_id", requestID,
	)

	return true, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*db.User, error) {
	requestID := middleware.GetRequestID(ctx)
	r.Logger.Debug("Fetching user by ID",
		"user_id", id,
		"request_id", requestID,
	)

	// Parse UUID
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Convert UUID to pgtype.UUID
	pgUserID := pgtype.UUID{
		Bytes: userID,
		Valid: true,
	}

	user, err := r.Queries.GetUser(ctx, pgUserID)
	if err != nil {
		r.Logger.Error("Failed to fetch user",
			"user_id", id,
			"error", err,
			"request_id", requestID,
		)
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return &user, nil
}

// UserByFirebaseUID is the resolver for the userByFirebaseUid field.
func (r *queryResolver) UserByFirebaseUID(ctx context.Context, firebaseUID string) (*db.User, error) {
	requestID := middleware.GetRequestID(ctx)
	r.Logger.Debug("Fetching user by Firebase UID",
		"firebase_uid", firebaseUID,
		"request_id", requestID,
	)

	user, err := r.Queries.GetUserByFirebaseUID(ctx, firebaseUID)
	if err != nil {
		r.Logger.Error("Failed to fetch user by Firebase UID",
			"firebase_uid", firebaseUID,
			"error", err,
			"request_id", requestID,
		)
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return &user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*db.User, error) {
	// This will be implemented after authentication is added
	// For now, return an error
	return nil, fmt.Errorf("authentication not yet implemented")
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	// Check database connection
	if err := r.DB.Ping(ctx); err != nil {
		return "unhealthy", fmt.Errorf("database connection failed: %w", err)
	}
	return "healthy", nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *db.User) (string, error) {
	if !obj.ID.Valid {
		return "", fmt.Errorf("invalid user ID")
	}
	// Convert pgtype.UUID bytes to UUID string
	id, err := uuid.FromBytes(obj.ID.Bytes[:])
	if err != nil {
		return "", fmt.Errorf("failed to convert UUID: %w", err)
	}
	return id.String(), nil
}

// ProfileImageURL is the resolver for the profileImageUrl field.
func (r *userResolver) ProfileImageURL(ctx context.Context, obj *db.User) (*string, error) {
	if obj.ProfileImageUrl.Valid {
		return &obj.ProfileImageUrl.String, nil
	}
	return nil, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *db.User) (*time.Time, error) {
	createdAt := obj.CreatedAt.Time
	return &createdAt, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *db.User) (*time.Time, error) {
	updatedAt := obj.UpdatedAt.Time
	return &updatedAt, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }