package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/fernandobandeira/djinn/backend/internal/application/dto"
	"github.com/fernandobandeira/djinn/backend/internal/graph/generated"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input dto.CreateUserInput) (*dto.UserDTO, error) {
	return r.CreateUserHandler.Handle(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input dto.UpdateUserInput) (*dto.UserDTO, error) {
	return r.UpdateUserHandler.Handle(ctx, id, input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	err := r.DeleteUserHandler.Handle(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*dto.UserDTO, error) {
	return r.GetUserHandler.Handle(ctx, id)
}

// UserByFirebaseUID is the resolver for the userByFirebaseUid field.
func (r *queryResolver) UserByFirebaseUID(ctx context.Context, firebaseUID string) (*dto.UserDTO, error) {
	return r.GetUserByFirebaseUIDHandler.Handle(ctx, firebaseUID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dto.UserDTO, error) {
	// TODO: Extract Firebase UID from context (requires auth middleware)
	// For now, returning an error
	return nil, fmt.Errorf("authentication required: me query requires auth middleware implementation")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
