package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/fernandobandeira/djinn/backend/internal/application/dto"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input dto.CreateUserInput) (*dto.UserDTO, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input dto.UpdateUserInput) (*dto.UserDTO, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*dto.UserDTO, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// UserByFirebaseUID is the resolver for the userByFirebaseUid field.
func (r *queryResolver) UserByFirebaseUID(ctx context.Context, firebaseUID string) (*dto.UserDTO, error) {
	panic(fmt.Errorf("not implemented: UserByFirebaseUID - userByFirebaseUid"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dto.UserDTO, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}
