// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	FirebaseUid     string         `db:"firebase_uid" json:"firebase_uid"`
	Email           string         `db:"email" json:"email"`
	Name            string         `db:"name" json:"name"`
	ProfileImageUrl sql.NullString `db:"profile_image_url" json:"profile_image_url"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time      `db:"updated_at" json:"updated_at"`
}
