// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	FirebaseUid     string             `db:"firebase_uid" json:"firebase_uid"`
	Email           string             `db:"email" json:"email"`
	Name            string             `db:"name" json:"name"`
	ProfileImageUrl pgtype.Text        `db:"profile_image_url" json:"profile_image_url"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
