// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Count total number of users for pagination
	CountUsers(ctx context.Context) (int64, error)
	// Create a new user account
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Delete a user account (soft delete could be implemented later)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	// Delete a user by Firebase UID
	DeleteUserByFirebaseUID(ctx context.Context, firebaseUid string) error
	// Get recently created users (for admin/analytics)
	GetRecentUsers(ctx context.Context, arg GetRecentUsersParams) ([]User, error)
	// User CRUD operations for Djinn personal finance application
	// Generated queries will be type-safe with pgx/v5
	// Get a user by their ID
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	// Get a user by their email address
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Get a user by their Firebase UID for authentication
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	// List users with pagination support
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Update user profile information
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Update user profile by Firebase UID (for auth flows)
	UpdateUserByFirebaseUID(ctx context.Context, arg UpdateUserByFirebaseUIDParams) (User, error)
	// Check if a user exists by ID
	UserExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// Check if a user exists by email
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	// Check if a user exists by Firebase UID
	UserExistsByFirebaseUID(ctx context.Context, firebaseUid string) (bool, error)
}

var _ Querier = (*Queries)(nil)
