// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

// Count total number of users for pagination
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, email, name, profile_image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, firebase_uid, email, name, profile_image_url, created_at, updated_at
`

type CreateUserParams struct {
	FirebaseUid     string         `db:"firebase_uid" json:"firebase_uid"`
	Email           string         `db:"email" json:"email"`
	Name            string         `db:"name" json:"name"`
	ProfileImageUrl sql.NullString `db:"profile_image_url" json:"profile_image_url"`
}

// Create a new user account
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirebaseUid,
		arg.Email,
		arg.Name,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Name,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

// Delete a user account (soft delete could be implemented later)
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserByFirebaseUID = `-- name: DeleteUserByFirebaseUID :exec
DELETE FROM users
WHERE firebase_uid = $1
`

// Delete a user by Firebase UID
func (q *Queries) DeleteUserByFirebaseUID(ctx context.Context, firebaseUid string) error {
	_, err := q.db.Exec(ctx, deleteUserByFirebaseUID, firebaseUid)
	return err
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, firebase_uid, email, name, profile_image_url, created_at, updated_at
FROM users
WHERE created_at >= $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentUsersParams struct {
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	Limit     int32     `db:"limit" json:"limit"`
}

// Get recently created users (for admin/analytics)
func (q *Queries) GetRecentUsers(ctx context.Context, arg GetRecentUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getRecentUsers, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Email,
			&i.Name,
			&i.ProfileImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one

SELECT id, firebase_uid, email, name, profile_image_url, created_at, updated_at
FROM users
WHERE id = $1
`

// User CRUD operations for Djinn personal finance application
// Generated queries will be type-safe with pgx/v5
// Get a user by their ID
func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Name,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firebase_uid, email, name, profile_image_url, created_at, updated_at
FROM users
WHERE email = $1
`

// Get a user by their email address
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Name,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, name, profile_image_url, created_at, updated_at
FROM users
WHERE firebase_uid = $1
`

// Get a user by their Firebase UID for authentication
func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Name,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, firebase_uid, email, name, profile_image_url, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// List users with pagination support
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Email,
			&i.Name,
			&i.ProfileImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    email = COALESCE($2, email),
    name = COALESCE($3, name),
    profile_image_url = COALESCE($4, profile_image_url)
WHERE id = $1
RETURNING id, firebase_uid, email, name, profile_image_url, created_at, updated_at
`

type UpdateUserParams struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	Email           string         `db:"email" json:"email"`
	Name            string         `db:"name" json:"name"`
	ProfileImageUrl sql.NullString `db:"profile_image_url" json:"profile_image_url"`
}

// Update user profile information
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Name,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByFirebaseUID = `-- name: UpdateUserByFirebaseUID :one
UPDATE users
SET 
    email = COALESCE($2, email),
    name = COALESCE($3, name),
    profile_image_url = COALESCE($4, profile_image_url)
WHERE firebase_uid = $1
RETURNING id, firebase_uid, email, name, profile_image_url, created_at, updated_at
`

type UpdateUserByFirebaseUIDParams struct {
	FirebaseUid     string         `db:"firebase_uid" json:"firebase_uid"`
	Email           string         `db:"email" json:"email"`
	Name            string         `db:"name" json:"name"`
	ProfileImageUrl sql.NullString `db:"profile_image_url" json:"profile_image_url"`
}

// Update user profile by Firebase UID (for auth flows)
func (q *Queries) UpdateUserByFirebaseUID(ctx context.Context, arg UpdateUserByFirebaseUIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserByFirebaseUID,
		arg.FirebaseUid,
		arg.Email,
		arg.Name,
		arg.ProfileImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Name,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

// Check if a user exists by ID
func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

// Check if a user exists by email
func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByFirebaseUID = `-- name: UserExistsByFirebaseUID :one
SELECT EXISTS(SELECT 1 FROM users WHERE firebase_uid = $1)
`

// Check if a user exists by Firebase UID
func (q *Queries) UserExistsByFirebaseUID(ctx context.Context, firebaseUid string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByFirebaseUID, firebaseUid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
