with-expecter: true
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "mock_{{.InterfaceName}}.go"
all: false
packages:
  github.com/fernandobandeira/djinn/backend/internal/infrastructure/persistence/postgres/generated:
    interfaces:
      Querier:
        config:
          dir: "internal/infrastructure/persistence/postgres/mocks"