// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fernandobandeira/djinn/backend/internal/infrastructure/config"
	"github.com/fernandobandeira/djinn/backend/internal/infrastructure/logging"
)

// Injectors from wire.go:

// InitializeApp creates a new lifecycle-managed application
func InitializeApp() (*Application, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	logger := logging.NewLogger(configConfig)
	application, err := NewApplication(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	return application, func() {
	}, nil
}
