// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fernandobandeira/djinn/backend/internal/config"
	"github.com/fernandobandeira/djinn/backend/internal/database"
	"github.com/fernandobandeira/djinn/backend/internal/logger"
	"github.com/fernandobandeira/djinn/backend/internal/server"
)

// Injectors from wire.go:

// InitializeApp creates a new server with all dependencies injected
func InitializeApp() (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	slogLogger := logger.New(configConfig)
	db, err := provideDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(configConfig, slogLogger, db)
	application := NewApplication(configConfig, slogLogger, db, serverServer)
	return application, nil
}

// wire.go:

// provideDatabase creates a database connection from config
func provideDatabase(cfg *config.Config) (*database.DB, error) {
	return database.Connect(cfg.PgBouncerURL)
}
