// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeApp creates a new application with all dependencies injected
func InitializeApp() (*Application, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger(config)
	db, err := ProvideDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	server := ProvideServer(config, logger, db)
	v, err := ProvideTracing(config)
	if err != nil {
		return nil, err
	}
	application := ProvideApplication(config, logger, db, server, v)
	return application, nil
}
