// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/fernandobandeira/djinn/backend/internal/database/db"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CountUsers provides a mock function with given fields: ctx
func (_m *MockQuerier) CountUsers(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountUsers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CountUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUsers'
type MockQuerier_CountUsers_Call struct {
	*mock.Call
}

// CountUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) CountUsers(ctx interface{}) *MockQuerier_CountUsers_Call {
	return &MockQuerier_CountUsers_Call{Call: _e.mock.On("CountUsers", ctx)}
}

func (_c *MockQuerier_CountUsers_Call) Run(run func(ctx context.Context)) *MockQuerier_CountUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_CountUsers_Call) Return(_a0 int64, _a1 error) *MockQuerier_CountUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CountUsers_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockQuerier_CountUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(_a0 db.User, _a1 error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.User, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockQuerier_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockQuerier_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockQuerier_DeleteUser_Call {
	return &MockQuerier_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockQuerier_DeleteUser_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockQuerier_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteUser_Call) Return(_a0 error) *MockQuerier_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteUser_Call) RunAndReturn(run func(context.Context, pgtype.UUID) error) *MockQuerier_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByFirebaseUID provides a mock function with given fields: ctx, firebaseUid
func (_m *MockQuerier) DeleteUserByFirebaseUID(ctx context.Context, firebaseUid string) error {
	ret := _m.Called(ctx, firebaseUid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByFirebaseUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, firebaseUid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteUserByFirebaseUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByFirebaseUID'
type MockQuerier_DeleteUserByFirebaseUID_Call struct {
	*mock.Call
}

// DeleteUserByFirebaseUID is a helper method to define mock.On call
//   - ctx context.Context
//   - firebaseUid string
func (_e *MockQuerier_Expecter) DeleteUserByFirebaseUID(ctx interface{}, firebaseUid interface{}) *MockQuerier_DeleteUserByFirebaseUID_Call {
	return &MockQuerier_DeleteUserByFirebaseUID_Call{Call: _e.mock.On("DeleteUserByFirebaseUID", ctx, firebaseUid)}
}

func (_c *MockQuerier_DeleteUserByFirebaseUID_Call) Run(run func(ctx context.Context, firebaseUid string)) *MockQuerier_DeleteUserByFirebaseUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_DeleteUserByFirebaseUID_Call) Return(_a0 error) *MockQuerier_DeleteUserByFirebaseUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteUserByFirebaseUID_Call) RunAndReturn(run func(context.Context, string) error) *MockQuerier_DeleteUserByFirebaseUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentUsers provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetRecentUsers(ctx context.Context, arg db.GetRecentUsersParams) ([]db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentUsers")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRecentUsersParams) ([]db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRecentUsersParams) []db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetRecentUsersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetRecentUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentUsers'
type MockQuerier_GetRecentUsers_Call struct {
	*mock.Call
}

// GetRecentUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetRecentUsersParams
func (_e *MockQuerier_Expecter) GetRecentUsers(ctx interface{}, arg interface{}) *MockQuerier_GetRecentUsers_Call {
	return &MockQuerier_GetRecentUsers_Call{Call: _e.mock.On("GetRecentUsers", ctx, arg)}
}

func (_c *MockQuerier_GetRecentUsers_Call) Run(run func(ctx context.Context, arg db.GetRecentUsersParams)) *MockQuerier_GetRecentUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetRecentUsersParams))
	})
	return _c
}

func (_c *MockQuerier_GetRecentUsers_Call) Return(_a0 []db.User, _a1 error) *MockQuerier_GetRecentUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetRecentUsers_Call) RunAndReturn(run func(context.Context, db.GetRecentUsersParams) ([]db.User, error)) *MockQuerier_GetRecentUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetUser(ctx context.Context, id pgtype.UUID) (db.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockQuerier_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockQuerier_Expecter) GetUser(ctx interface{}, id interface{}) *MockQuerier_GetUser_Call {
	return &MockQuerier_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockQuerier_GetUser_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockQuerier_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetUser_Call) Return(_a0 db.User, _a1 error) *MockQuerier_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUser_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (db.User, error)) *MockQuerier_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockQuerier_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerier_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockQuerier_GetUserByEmail_Call {
	return &MockQuerier_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockQuerier_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) Return(_a0 db.User, _a1 error) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByFirebaseUID provides a mock function with given fields: ctx, firebaseUid
func (_m *MockQuerier) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (db.User, error) {
	ret := _m.Called(ctx, firebaseUid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByFirebaseUID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, firebaseUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, firebaseUid)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, firebaseUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByFirebaseUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByFirebaseUID'
type MockQuerier_GetUserByFirebaseUID_Call struct {
	*mock.Call
}

// GetUserByFirebaseUID is a helper method to define mock.On call
//   - ctx context.Context
//   - firebaseUid string
func (_e *MockQuerier_Expecter) GetUserByFirebaseUID(ctx interface{}, firebaseUid interface{}) *MockQuerier_GetUserByFirebaseUID_Call {
	return &MockQuerier_GetUserByFirebaseUID_Call{Call: _e.mock.On("GetUserByFirebaseUID", ctx, firebaseUid)}
}

func (_c *MockQuerier_GetUserByFirebaseUID_Call) Run(run func(ctx context.Context, firebaseUid string)) *MockQuerier_GetUserByFirebaseUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserByFirebaseUID_Call) Return(_a0 db.User, _a1 error) *MockQuerier_GetUserByFirebaseUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByFirebaseUID_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockQuerier_GetUserByFirebaseUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByIDs provides a mock function with given fields: ctx, dollar_1
func (_m *MockQuerier) GetUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]db.User, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIDs")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []pgtype.UUID) ([]db.User, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []pgtype.UUID) []db.User); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []pgtype.UUID) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUsersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByIDs'
type MockQuerier_GetUsersByIDs_Call struct {
	*mock.Call
}

// GetUsersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - dollar_1 []pgtype.UUID
func (_e *MockQuerier_Expecter) GetUsersByIDs(ctx interface{}, dollar_1 interface{}) *MockQuerier_GetUsersByIDs_Call {
	return &MockQuerier_GetUsersByIDs_Call{Call: _e.mock.On("GetUsersByIDs", ctx, dollar_1)}
}

func (_c *MockQuerier_GetUsersByIDs_Call) Run(run func(ctx context.Context, dollar_1 []pgtype.UUID)) *MockQuerier_GetUsersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetUsersByIDs_Call) Return(_a0 []db.User, _a1 error) *MockQuerier_GetUsersByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUsersByIDs_Call) RunAndReturn(run func(context.Context, []pgtype.UUID) ([]db.User, error)) *MockQuerier_GetUsersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListUsersParams) ([]db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListUsersParams) []db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListUsersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockQuerier_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListUsersParams
func (_e *MockQuerier_Expecter) ListUsers(ctx interface{}, arg interface{}) *MockQuerier_ListUsers_Call {
	return &MockQuerier_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, arg)}
}

func (_c *MockQuerier_ListUsers_Call) Run(run func(ctx context.Context, arg db.ListUsersParams)) *MockQuerier_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListUsersParams))
	})
	return _c
}

func (_c *MockQuerier_ListUsers_Call) Return(_a0 []db.User, _a1 error) *MockQuerier_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListUsers_Call) RunAndReturn(run func(context.Context, db.ListUsersParams) ([]db.User, error)) *MockQuerier_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockQuerier_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserParams
func (_e *MockQuerier_Expecter) UpdateUser(ctx interface{}, arg interface{}) *MockQuerier_UpdateUser_Call {
	return &MockQuerier_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *MockQuerier_UpdateUser_Call) Run(run func(ctx context.Context, arg db.UpdateUserParams)) *MockQuerier_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateUser_Call) Return(_a0 db.User, _a1 error) *MockQuerier_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateUser_Call) RunAndReturn(run func(context.Context, db.UpdateUserParams) (db.User, error)) *MockQuerier_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByFirebaseUID provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUserByFirebaseUID(ctx context.Context, arg db.UpdateUserByFirebaseUIDParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByFirebaseUID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserByFirebaseUIDParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserByFirebaseUIDParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateUserByFirebaseUIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateUserByFirebaseUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByFirebaseUID'
type MockQuerier_UpdateUserByFirebaseUID_Call struct {
	*mock.Call
}

// UpdateUserByFirebaseUID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserByFirebaseUIDParams
func (_e *MockQuerier_Expecter) UpdateUserByFirebaseUID(ctx interface{}, arg interface{}) *MockQuerier_UpdateUserByFirebaseUID_Call {
	return &MockQuerier_UpdateUserByFirebaseUID_Call{Call: _e.mock.On("UpdateUserByFirebaseUID", ctx, arg)}
}

func (_c *MockQuerier_UpdateUserByFirebaseUID_Call) Run(run func(ctx context.Context, arg db.UpdateUserByFirebaseUIDParams)) *MockQuerier_UpdateUserByFirebaseUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserByFirebaseUIDParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateUserByFirebaseUID_Call) Return(_a0 db.User, _a1 error) *MockQuerier_UpdateUserByFirebaseUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateUserByFirebaseUID_Call) RunAndReturn(run func(context.Context, db.UpdateUserByFirebaseUIDParams) (db.User, error)) *MockQuerier_UpdateUserByFirebaseUID_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function with given fields: ctx, id
func (_m *MockQuerier) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type MockQuerier_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockQuerier_Expecter) UserExists(ctx interface{}, id interface{}) *MockQuerier_UserExists_Call {
	return &MockQuerier_UserExists_Call{Call: _e.mock.On("UserExists", ctx, id)}
}

func (_c *MockQuerier_UserExists_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockQuerier_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_UserExists_Call) Return(_a0 bool, _a1 error) *MockQuerier_UserExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UserExists_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (bool, error)) *MockQuerier_UserExists_Call {
	_c.Call.Return(run)
	return _c
}

// UserExistsByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerier) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserExistsByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UserExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExistsByEmail'
type MockQuerier_UserExistsByEmail_Call struct {
	*mock.Call
}

// UserExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerier_Expecter) UserExistsByEmail(ctx interface{}, email interface{}) *MockQuerier_UserExistsByEmail_Call {
	return &MockQuerier_UserExistsByEmail_Call{Call: _e.mock.On("UserExistsByEmail", ctx, email)}
}

func (_c *MockQuerier_UserExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerier_UserExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_UserExistsByEmail_Call) Return(_a0 bool, _a1 error) *MockQuerier_UserExistsByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UserExistsByEmail_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockQuerier_UserExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserExistsByFirebaseUID provides a mock function with given fields: ctx, firebaseUid
func (_m *MockQuerier) UserExistsByFirebaseUID(ctx context.Context, firebaseUid string) (bool, error) {
	ret := _m.Called(ctx, firebaseUid)

	if len(ret) == 0 {
		panic("no return value specified for UserExistsByFirebaseUID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, firebaseUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, firebaseUid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, firebaseUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UserExistsByFirebaseUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExistsByFirebaseUID'
type MockQuerier_UserExistsByFirebaseUID_Call struct {
	*mock.Call
}

// UserExistsByFirebaseUID is a helper method to define mock.On call
//   - ctx context.Context
//   - firebaseUid string
func (_e *MockQuerier_Expecter) UserExistsByFirebaseUID(ctx interface{}, firebaseUid interface{}) *MockQuerier_UserExistsByFirebaseUID_Call {
	return &MockQuerier_UserExistsByFirebaseUID_Call{Call: _e.mock.On("UserExistsByFirebaseUID", ctx, firebaseUid)}
}

func (_c *MockQuerier_UserExistsByFirebaseUID_Call) Run(run func(ctx context.Context, firebaseUid string)) *MockQuerier_UserExistsByFirebaseUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_UserExistsByFirebaseUID_Call) Return(_a0 bool, _a1 error) *MockQuerier_UserExistsByFirebaseUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UserExistsByFirebaseUID_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockQuerier_UserExistsByFirebaseUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
